all:
	gcc -c -g -Wall ../../../Data-Structures/double_linked_list/double_linked_list.c
	gcc -c -g -Wall graph_matrix.c
	
	gcc -o ./objects/graph_matrix double_linked_list.o graph_matrix.o
	
	mv *.o ./objects
