all:
	gcc -c -g -Wall graph_algorithms.c
	gcc -c -g -Wall  ../../Data-Structures/double_linked_list/double_linked_list.c
	gcc -g -Wall -o ./objects/graph_algorithms graph_algorithms.o double_linked_list.o
	mv *.o ./objects
